-nbad -bap -bfda -nbc -bbo -hnl -br -brf -brs -c33 -cd33 -ncdb -cdw -ce -ci8 -cli0 -d0 -di1 -nfc1 -i8 -ip0 -l0 -nlp -npcs -nprs -npsl -sai -saf -saw -nbs -cs -sc -sob -nfca -cp33 -ss -ts8 -il1 -lc80 -ppi8
-T bool
-T FILE
-T GAsyncResult
-T gboolean
-T gchar
-T gint
-T gpointer
-T GSimpleAsyncResult
-T gunichar
-T size_t
